export const MONGO_CLIENT_NAME = 'MONGO_CLIENT_NAME';
export const DB_CONNECTION = 'DB_CONNECTION';
export const MONGO_CLIENT = 'MONGO_CLIENT';
export const MONGO_MODULE_OPTIONS = 'MONGO_MODULE_OPTIONS';
